#+Title: My Config
#+Property: header-args :tangle config.el
#+Property: header-args :results silent
#+Startup: overview

* General
** Compile-angel
Ensure all loaded .el files are compiled beforehand.
#+begin_src elisp :tangle packages.el
(package! compile-angel)
#+end_src

This shoudl be in ~early-init.el~, but I am not sure how to do so in doom's emacs:
#+begin_src elisp
(setq load-prefer-newer t)
#+end_src

#+begin_src elisp
(use-package compile-angel
  :demand t
  :config
  ;; Uncomment the line below to compile automatically when an Elisp file is saved
  (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode)

  ;; The following directive prevents compile-angel from compiling your init
  ;; files. If you choose to remove this push to `compile-angel-excluded-files'
  ;; and compile your pre/post-init files, ensure you understand the
  ;; implications and thoroughly test your code. For example, if you're using
  ;; the `use-package' macro, you'll need to explicitly add:
  ;; (eval-when-compile (require 'use-package))
  ;; at the top of your init file.
  (push "/init.el" compile-angel-excluded-files)
  (push "/early-init.el" compile-angel-excluded-files)

  ;; A global mode that compiles .el files before they are loaded
  ;; using `load' or `require'.
  (compile-angel-on-load-mode 1))
#+end_src
** General
#+begin_src elisp
(after! doom
  (setq user-full-name "Ieremies V. F. Romero"
        user-mail-address "ieremies@gmail.com"
        doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 14)
        mixed-pitch-set-height 't
        doom-theme 'nano-light

        evil-want-fine-undo t
        truncate-string-ellipsis "…"

        x-underline-at-descent-line 't
        widget-image-enable 'nil ;; no ugly button for checkboxes
        org-hide-emphasis-markers 't ;; Hide org markup

        menu-bar-mode -1
        ))

(set-face-attribute 'variable-pitch nil
                        ;; :family "NotoSans Nerd Font"
                        :family "Hanken Grotesk"
                        ;; :family "SF Pro Text"
                        ;; :family "Helvetica"
                        :height 150)

(setq-default delete-by-moving-to-trash t
              window-combination-resize t
              underline-minimum-offset 3
              x-underline-at-descent-line nil
              line-spacing 2
              menu-bar-mode -1)

(window-divider-mode 1)
(menu-bar-mode -1)
#+end_src

Some packages invoke the shell and the load of the respective rc file can be considerable.
#+begin_src elisp
(after! doom
  (setq inhibit-compacting-font-caches t
        display-line-numbers-type nil
        explicit-shell-file-name "/bin/bash"))
#+end_src

Configuration for MacOS.
#+begin_src elisp
(after! doom
  (setq frame-title-format " "
        ns-use-proxy-icon 'nil
        ns-use-native-fullscreen 'nil))
#+end_src

Default window configuration.
#+begin_src elisp
(after! doom
  (setq window-min-height 1
        window-divider-default-right-width 24
        window-divider-default-places 'right-only
        default-frame-alist (append (list
                                   '(min-height . 1)
                                   '(height     . 80)
                                   '(min-width  . 1)
                                   '(width      . 150)
                                   '(vertical-scroll-bars . nil)
                                   '(internal-border-width . 24)
                                   ;; '(fullscreen . maximized)
                                   '(undecorated-round . t)))))
#+end_src

** Nano-modeline
#+begin_src elisp :tangle packages.el
(package! doom-nano-modeline
  :recipe (:host github :repo "ronisbr/doom-nano-modeline"))
#+end_src
#+begin_src elisp
(use-package! doom-nano-modeline
  :after doom
  :config
  (doom-nano-modeline-mode 1)
  (global-hide-mode-line-mode 1))
#+end_src
* Checkers
** Spell
*** Jinx
#+begin_src elisp :tangle packages.el
(package! jinx
  :recipe (:host github :repo "minad/jinx"))
#+end_src
#+begin_src elisp
(use-package! jinx
  :hook
  (org-mode . jinx-mode)
  (typst-ts-mode . jinx-mode)
  :config
  (setq jinx-languages "en_US"
        jinx-delay 1.0)
  (nconc (cadr jinx-exclude-faces) '(org-ref-ref-face)))

(after! vertico-multiform
  (add-to-list 'vertico-multiform-categories
               '(jinx (vertico-grid-annotate . 25)))
  (vertico-multiform-mode 1))

(with-eval-after-load 'jinx
  (define-key jinx-overlay-map
    [down-mouse-1]
    `(menu-item "" (keymap) :filter ,#'jinx--correct-menu)))
#+end_src

Save misspelling and correction as abbreviation.
#+begin_src elisp
(after! jinx
  (defun jinx--add-to-abbrev (overlay word)
    "Add abbreviation to `global-abbrev-table'.
The misspelled word is taken from OVERLAY.  WORD is the corrected word."
    (let ((abbrev (buffer-substring-no-properties
                   (overlay-start overlay)
                   (overlay-end overlay))))
      (message "Abbrev: %s -> %s" abbrev word)
      (define-abbrev global-abbrev-table abbrev word)))

  (advice-add 'jinx--correct-replace :before #'jinx--add-to-abbrev))
#+end_src
* Completion
** corfu
#+begin_src emacs-lisp :tangle yes
(after! corfu
  (setq corfu-auto-delay 0.2
        text-mode-ispell-word-completion nil
        corfu-popupinfo-delay '(0.5 . 0.2)
        corfu-count 10)
  (set-face-attribute 'corfu-default nil
                      :background (face-attribute 'default :background))
  (set-face-attribute 'corfu-current nil
                      :background "#FAFAFA"))
#+end_src
I have twice ran into the problem of "no registered capabilities" for an LSP.
It seems to be solved by deleting =~.config/emacs/eln-cache= and rebuilding it all.
** hotfuzz+orderless
#+begin_src elisp :tangle packages.el
(package! hotfuzz
  :recipe (:host github :repo "axelf4/hotfuzz"))
#+end_src
#+begin_src elisp
;;;###autoload
(defun hotfuzz+orderless-all-completions (str table pred pt)
  (let ((words (split-string str nil t)))
    (orderless-all-completions
     (string-join (cdr words) " ")
     (if (car words)
         (nconc (hotfuzz-all-completions (car words) table pred pt) nil)
       table)
     pred pt)))

;;;###autoload
(progn
  (add-to-list 'completion-styles-alist
               '( hotfuzz+orderless orderless-try-completion hotfuzz+orderless-all-completions
                  "Filter first component with Hotfuzz, rest with Orderless."))
  (put 'hotfuzz+orderless 'completion--adjust-metadata #'hotfuzz--adjust-metadata))
#+end_src
* Editor
** Evil
#+begin_src elisp
(after! evil
  (setq evil-ex-substitute-global t
        evil-kill-on-visual-paste nil
        evil-vsplit-window-right t
        evil-split-window-below t)
  ;; Center cursor on screen after search
  (advice-add 'evil-ex-search-next :after
              (lambda (&rest x) (evil-scroll-line-to-center (line-number-at-pos))))
  (advice-add 'evil-ex-search-previous :after
              (lambda (&rest x) (evil-scroll-line-to-center (line-number-at-pos)))))
#+end_src
* Emacs
** dired +dirvish
#+begin_src emacs-lisp :tangle yes
(after! dirvish
  (dirvish-side-follow-mode)
  (setq dirvish-side-width 25))
#+end_src
*** IDEA In dirvish
When pressing ~tab~, it triggers ~dirvish-subtree-toggle~, the selection buffer does appear, the cursor previews on the background, but, after selecting and pressing ~RET~, nothing happens and the cursor comes
** buffer-terminator
#+begin_src emacs-lisp :tangle packages.el
(package! buffer-terminator)
#+end_src
#+begin_src emacs-lisp :tangle yes
(use-package buffer-terminator
  :custom
  (buffer-terminator-verbose nil)

  ;; Set the inactivity timeout (in seconds) after which buffers are considered
  ;; inactive (default is 30 minutes):
  (buffer-terminator-inactivity-timeout (* 30 60)) ; 30 minutes

  ;; Define how frequently the cleanup process should run (default is every 10
  ;; minutes):
  (buffer-terminator-interval (* 10 60)) ; 10 minutes

  :config
  (buffer-terminator-mode 1))
#+end_src
** Buffer to pdf
#+begin_src emacs-lisp :tangle packages.el
(package! buffer-to-pdf
  :recipe (:host github :repo "protesilaos/buffer-to-pdf"))
#+end_src
#+begin_src emacs-lisp :tangle yes
(use-package! buffer-to-pdf
  :config
  ;; Configure `buffer-to-pdf-directory' to specify where PDF files are stored.
  ;; This is the default value:
  (setq buffer-to-pdf-directory (expand-file-name "~/Downloads/")))
#+end_src
* Languages
** CC
#+begin_src elisp
(setq my/clangd-args
      '("-j=3"
        "--background-index"
        "--clang-tidy"
        "--completion-style=detailed"
        "--header-insertion=never"
        "--header-insertion-decorators=0"))

(after! (lsp-mode lsp-clangd)
  (setq lsp-clients-clangd-args my/clangd-args)
  (set-lsp-priority! 'clangd 2))

(after! eglot
  (set-eglot-client! 'cc-mode (append '("clangd") my/clangd-args)))
#+end_src

** Python
*** Ruff
#+begin_src elisp
;; (after! eglot
;;   (add-hook 'python-mode-hook 'eglot-ensure)
;;   (with-eval-after-load 'eglot
;;     (add-to-list 'eglot-server-programs
;;                  '(python-mode . ("ruff" "server")))
;;     (add-hook 'after-save-hook 'eglot-format)))

;; Replace default (black) to use ruff for sorting import and formatting.
(after! apheleia
  (setf (alist-get 'python-mode apheleia-mode-alist)
        '(ruff-isort ruff))
  (setf (alist-get 'python-ts-mode apheleia-mode-alist)
        '(ruff-isort ruff)))
#+end_src
** LaTeX
#+begin_src emacs-lisp :tangle yes
(after! tex
(setq TeX-engine-alist '((default
                          "Tectonic"
                          "tectonic -X compile -f plain %T"
                          "tectonic -X watch"
                          nil))
      LaTeX-command-style '(("" "%(latex)"))
      TeX-process-asynchronous t
      TeX-check-TeX nil
      TeX-engine 'default)

(let ((tex-list (assoc "TeX" TeX-command-list))
      (latex-list (assoc "LaTeX" TeX-command-list)))
  (setf (cadr tex-list) "%(tex)"
        (cadr latex-list) "%l")))
#+end_src
* Org-mode
** General
#+begin_src elisp
(after! org
  (setq org-directory "~/org/"
        org-log-done 'time ; log when a task was closed
        org-archive-location ".%s_archive::"
        org-export-allow-bind-keywords 't
        org-image-actual-width '(0.9)
        org-ellipsis "…"
        +fold-ellipsis org-ellipsis)

  (map! :leader :desc "Paste org subtree" "m s p"#'org-paste-subtree
                :desc "Yank org subtree"  "m s y"#'org-copy-subtree
                ;; switching capture with scratch
                :desc "Org capture"    "x"#'org-capture
                :desc "Scratch buffer" "X"#'doom/open-scratch-buffer)

  ;; (after! hl-todo
  ;;   (add-hook 'org-mode-hook (lambda () (hl-todo-mode 1))))
  (add-hook 'org-mode-hook (lambda () (org-num-mode 1))))
#+end_src
*** Mixed pitch
The =mixed-pitch-mode= reverts back to the default =fixed-pitch :weight= value when a face is in =mixed-pitch-fixed-pitch-faces=.
#+begin_src diff :tangle no
-                              face :family fix-pitch :height fix-height :weight fix-weight)
-                           (face-remap-add-relative face :family fix-pitch :weight fix-weight))))
+                              face :family fix-pitch :height fix-height)
+                           (face-remap-add-relative face :family fix-pitch))))
#+end_src
#+begin_src elisp :tangle packages.el
(package! mixed-pitch)
#+end_src
#+begin_src elisp
(use-package! mixed-pitch
  :hook
  (org-mode . mixed-pitch-mode)
  (typst-ts-mode . mixed-pitch-mode)
  )
#+end_src

*** org-appear
Toggle the appearance of hidden elements in org-mode.
#+begin_src elisp :tangle packages.el
(package! org-appear
  :recipe (:host github :repo "awth13/org-appear"))
#+end_src
#+begin_src elisp
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  (setq org-hide-emphasis-markers 't
        org-appear-autoemphasis   't
        org-appear-autolinks      't
        org-appear-autosubmarkers 't
        org-appear-inside-latex   't)
  ;; for proper first-time setup, `org-appear--set-elements'
  ;; needs to be run after other hooks have acted.
  (run-at-time nil nil #'org-appear--set-elements))
#+end_src
*** org-modern
#+begin_src emacs-lisp :tangle packages.el
(package! org-modern
  :recipe (:host github :repo "minad/org-modern"))
(package! org-modern-indent
  :recipe (:host github :repo "jdtsmith/org-modern-indent"))
#+end_src

#+begin_src emacs-lisp :tangle yes
(use-package org-modern
  :custom
  (org-modern-hide-stars nil)
  (org-modern-table nil)
  (org-modern-todo nil)
  (org-modern-fold-stars '(("▸" . "▾")))
  (org-modern-list '((?* . "•") (?+ . "‣")))
  (org-auto-align-tags nil)
  (org-pretty-entities t)
  :hook
  (org-mode . org-modern-mode)
  (org-agenda-finalize . org-modern-agenda))

(use-package org-modern-indent
  :config
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90))
#+end_src
** Annotation
*** org-roam
#+begin_src emacs-lisp :tangle yes
(after! org-roam
  (setq org-roam-directory "~/org/"))
#+end_src
*** citar-org-roam
#+begin_src elisp :tangle yes
(use-package citar-org-roam
  :after (citar org-roam)
  :config
  (citar-org-roam-mode)
  (add-to-list  'org-roam-capture-templates
                '("r" "bibliography reference" plain
                  ;; BUG Fix file name
"#+Subtitle: ${citar-journaltitle} - ${citar-year}
,#+Author: ${citar-author}
,#+filetags: reference"
                  :target (file+head "ref/${citar-citekey}.org"
                                     "#+Title: ${citar-title}\n")))
  (setq citar-org-roam-capture-template-key "r"
        citar-org-roam-note-title-template "${title}")

  (add-to-list 'citar-org-roam-template-fields '(:citar-year "date"))
  (add-to-list 'citar-org-roam-template-fields '(:citar-file "file"))
  (add-to-list 'citar-org-roam-template-fields '(:citar-journaltitle "journaltitle" "booktitle")))
#+end_src
** Citations and references
*** org-cite
#+begin_src elisp
(after! oc
  (setq org-cite-biblatex-options
        (string-join
         '("date=year"
           "backend=biber"
           "url=false"
           "isbn=false"
           "sortcites=true"
           "sorting=nty")
         ",")
        org-cite-export-processors
        `((latex . (biblatex "style=numeric-comp,bibstyle=ieee" "auto"))
          (t . basic))
        )
  )
#+end_src

*** citar
Already loaded by =:tools biblio=.
#+begin_src emacs-lisp
(after! citar
  (setq org-cite-global-bibliography '("/Users/ieremies/arq/bib.bib")
        citar-bibliography           '("/Users/ieremies/arq/bib.bib")
        citar-library-paths          '("/Users/ieremies/arq/files/")
        citar-notes-paths            '("/Users/ieremies/org/ref/")
        citar-bibliography           org-cite-global-bibliography)

  (map! :mode org-mode
        :desc "Insert a citation"
        :nvi "C-a" #'org-cite-insert))
#+end_src

*** oc-csl-activate
#+begin_src elisp :tangle packages.el
(package! oc-csl-activate
  :recipe (:host github :repo "andras-simonyi/org-cite-csl-activate"))
#+end_src
#+begin_src elisp
(use-package! oc-csl-activate
  :after oc
  :hook (org-mode . cursor-sensor-mode)
  :config
  (setq org-cite-activate-processor 'csl-activate
        org-cite-csl-activate-use-citar-cache t
        org-cite-csl-activate-use-document-style t))

(setq org-cite-activate-processor 'csl-activate)
#+end_src

*** org-ref (only ref links)
#+begin_src elisp :tangle packages.el
(package! org-ref-ref-links
  :recipe (:host github :repo "ieremies/org-ref"))
#+end_src
#+begin_src elisp
(use-package! org-ref-ref-links
  :config
  (setq org-ref-default-ref-type "cref")
  (add-to-list 'org-ref-ref-label-regexps
               (concat ":label\\s-+" org-ref-label-re "\\_>")))
#+end_src

** Latex
See [[https://tecosaur.github.io/emacs-config/config.html#latex-export][Tecosaur's config]].
Some small thing I want to add:
- [ ] automatically add the ~ before citations, references and inline math.
*** Org-mode config
#+begin_src elisp
(after! org
  (setq org-export-with-todo-keywords 'nil
        org-export-with-toc           'nil
        org-export-with-tags          'nil
        org-export-with-date          'nil
        org-latex-pdf-process '("tectonic -X compile --outdir=%o -Z shell-escape -Z continue-on-errors %f")
  ))
#+end_src

*** Default preamble
As explained on the help page of ~org-latex-classes~, the preamble is constructed based on

 - [DEFAULT-PACKAGES] :: come from ~org-latex-default-packages-alist~
 - [PACKAGES] :: comes from ~org-latex-packages-alist~
 - [EXTRA] :: the stuff from #+LATEX_HEADER(_EXTRA)

If the header (any package added) has ~\usepackage[AUTO]{babel}~, AUTO will be replaced with the language related to the language code specified by ~org-export-default-language~.
See ~org-latex-guess-babel-language~.
#+begin_src elisp
(after! org
  (add-to-list 'org-latex-packages-alist '("" "/Users/ieremies/arq/tex/myheader" t)))
#+end_src

*** Export folder
All exports are placed under a folder called build.
#+begin_src elisp
(defadvice org-export-output-file-name (before org-add-export-dir activate)
  "Modifies org-export to place exported files in a different directory"
  (when (not pub-dir)
      (setq pub-dir "build")
      (when (not (file-directory-p pub-dir))
       (make-directory pub-dir))))
#+end_src

*** Math highlighting
#+begin_src elisp
(after! org
  (setq org-highlight-latex-and-related '(native script entities)))
#+end_src

*** Smart quotes
Quotes for pt-br are missing.
#+begin_src elisp
(after! ox
  (add-to-list 'org-export-smart-quotes-alist
               '("pt-br"
                 (primary-opening :utf-8 "“" :html "&ldquo;" :latex "``" :texinfo "``")
                 (primary-closing :utf-8 "”" :html "&rdquo;" :latex "''" :texinfo "''")
                 (secondary-opening :utf-8 "‘" :html "&lsquo;" :latex "`" :texinfo "`")
                 (secondary-closing :utf-8 "’" :html "&rsquo;" :latex "'" :texinfo "'")
                 (apostrophe :utf-8 "’" :html "&rsquo;"))))
#+end_src
*** Code highlighting - [[https://github.com/tecosaur/engrave-faces][tecosaur/engrave-faces]]
Seems to have a substantial overhead on compile.
Just check wheter this affects any other pdf that does not contain it.
#+begin_src elisp :tangle packages.el
(package! engrave-faces
  :recipe (:host github :repo "tecosaur/engrave-faces"))
#+end_src
#+begin_src elisp
;; TODO something has changed in org 9.6
(use-package! engrave-faces-latex
  :after ox-latex)
(after! engrave-faces
  (setq org-latex-listings 'engraved))
#+end_src
*** Math symbols
Math symbols that are put in place of the commands are kinda small compared to the default font.
By doing a face-font-rescale, for some reason, the first two levels of org-modern are also scaled
#+begin_src elisp
(push `("Apple Symbols" . ,(/ 19.0 13.0)) face-font-rescale-alist)
#+end_src
*** Beamer
#+begin_src elisp
(setq org-beamer-theme "[progressbar=foot]metropolis"
      org-beamer-frame-level 2)
#+end_src
** org-special-blocks-extra
#+begin_src elisp :tangle packages.el
(package! org-special-block-extras)
#+end_src

#+begin_src emacs-lisp 
(use-package! org-special-block-extras
  :after org
  :config
  (org-deflink todo
               "Exports a 'todo' link to Typst syntax #todo[...]. 
In other backends, it just displays the description or label."
               ;; Optional: Make it look distinct in your Org buffer
               [:face '(:foreground "orange" :weight bold)
                :help-echo "Typst Todo: #todo[...]"]
               
               (cond
                ((equal o-backend 'typst)
                 (format "#todo[%s]" (or o-description o-label)))
                ;; Fallback for other backends (HTML, LaTeX, etc.)
                (t (or o-description o-label))))
  )
#+end_src
* UI
** Olivetti
#+begin_src emacs-lisp :tangle packages.el
(package! olivetti)
(package! auto-olivetti
  :recipe (:host sourcehut :repo "ashton314/auto-olivetti"))
#+end_src
#+begin_src emacs-lisp :tangle yes
(use-package! olivetti
  :hook (text-mode . olivetti-mode)
  :config (setq-default olivetti-body-width 70))
#+end_src
* Tools
** [[https://github.com/SavchenkoValeriy/emacs-powerthesaurus][SavchenkoValeriy/emacs-powerthesaurus]]
Use =powerthesaurus-lookup-dwim=.
#+begin_src elisp :tangle packages.el
(package! powerthesaurus)
#+end_src
** Debugger
DOOM's also has a debugger module, but dap-mode is the standard.
*** [[https://github.com/svaante/dape][svaante/dape]]
I have to use [[https://github.com/vadimcn/codelldb/blob/v1.10.0/MANUAL.md][codelldb]].
#+begin_src elisp :tangle packages.el
(package! dape-mode
  :recipe (:host github :repo "svaante/dape"))
#+end_src
#+begin_src elisp
(use-package dape
  :hook
  ((kill-emacs . dape-breakpoint-save)
   (after-init . dape-breakpoint-load))
  :config
  (setq dape-buffer-window-arrangement 'right
        dape-cwd-fn 'projectile-project-root)
  (dape-breakpoint-global-mode))
#+end_src
** LSP (eglot or LSP-mode)
#+begin_src emacs-lisp :tangle yes
(after! lsp-mode
  (add-hook! 'lsp-mode-hook (lambda () (lsp-inlay-hints-mode 1))))
#+end_src
[[https://www.reddit.com/r/emacs/comments/1n3o2we/on_macos_in_gui_with_eglot_turned_on_when_the/][See this]]
#+begin_src emacs-lisp :tangle yes
(after! eglot
  ;; 
  (setq eglot-code-action-indicator "*"))
#+end_src
* AI
** GPTel
Enabled by the =llm= doom module.
#+begin_src emacs-lisp :tangle yes
(after! gptel
  (setq
 gptel-model 'gemini-2.5-pro
 gptel-backend (gptel-make-gemini "Gemini"
                 :key ""
                 :stream t))
  )
#+end_src

** Completion / copilot
It causes around 0.3s of startup time.
#+begin_src elisp :tangle packages.el
(package! copilot
  :recipe (:host github :repo "copilot-emacs/copilot.el" :files ("*.el")))
#+end_src
#+begin_src elisp
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (:map copilot-completion-map
              ("C-[" . 'copilot-complete)
              ("C-]" . 'copilot-accept-completion)
              ("C-}" . 'copilot-accept-completion-by-word))
  :config
  (setq copilot-idle-delay 0.2))
#+end_src
